### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by tankhuu** [ExploreConsulting/NetSuite-Interface-Uploader#10]
I'm sorry but I don't know how to use it.

**Comment by EmilChoparinov** [comment]
there is a tutorial command or you can check this here:

https://github.com/ExploreConsulting/NetSuite-Interface-Uploader/blob/master/tutorial.MD

there's also lots of documentation online on how to use extensions in general:

https://code.visualstudio.com/docs/editor/extension-gallery

**Comment by EmilChoparinov** [comment]
Thanks!

If you find it useful, feedback is always welcome and be sure to rate it!
