### ISSUE TITLE
command 'nsi.uploadFile' not found

### ISSUE THREAD

**Issue by LeonOliveira** [ExploreConsulting/NetSuite-Interface-Uploader#9]
how to fix erro "command 'nsi.uploadFile' not found" with upload file on netsuite

**Comment by LeonOliveira** [comment]
while run the command NSI: Upload File

**Comment by EmilChoparinov** [comment]
did you run this command with a *.ts or *.js opened?

thanks

**Comment by EmilChoparinov** [comment]
just pushed out a patch @LeonOliveira, try updating the extension. seems to be working for me
